import type { AssetCategory, AssetPlacement, CatalogAsset, RoomActionType, RoomZoneType } from "@/lib/types";
import interiorV1 from "@/lib/asset-catalogs/nestudio-interior-v1.json";

// ── Nestudio Interior V1 — static catalog bridge (room-engine slice) ──
//
// This is the first connection between the isolated Asset Factory and the main
// app's room engine. The Factory's `roomEngineCatalog()` export (approved + real
// OpenAI Style Lab assets, with public Supabase image URLs) is committed here as a
// static JSON artifact and merged into `lib/assets.ts`. The room renderer then
// shows the real PNG art image-first (see ADR-021).
//
// STAND-IN NOTE: the genuine 28 Style Lab rows live in the Factory's Supabase
// (RLS-locked; not reachable in this environment), so this artifact currently
// ships self-contained stand-in PNGs from /public (generated by
// scripts/gen-interior-v1-placeholder-pngs.mjs), shaped identically to the real
// export. Replacing the JSON with the real Factory export is a one-file swap — no
// code change — because the loader and renderer key off "is this a real image
// URL", not off where the asset came from.

/** The provenance-carrying shape the Asset Factory exports (RoomEngineAsset). */
type InteriorCatalogRecord = {
  id: string;
  name: string;
  category: string;
  villageTheme: string;
  placement: string;
  ownerType: string;
  rarity: string;
  tags: string[];
  imageUrl: string;
  status: string;
  compatibleZones: string[];
  defaultScale: number;
  defaultActionType: string;
  personality?: string;
  source?: string;
  modelProvider?: string;
  modelName?: string;
};

const records = interiorV1 as InteriorCatalogRecord[];

/** The Interior V1 assets in the main app's `CatalogAsset` shape. */
export const interiorV1Assets: CatalogAsset[] = records.map((record) => ({
  id: record.id,
  name: record.name,
  category: record.category as AssetCategory,
  villageTheme: record.villageTheme,
  placement: record.placement as AssetPlacement,
  ownerType: "system",
  rarity: "common",
  tags: record.tags,
  imageUrl: record.imageUrl,
  status: "published",
  compatibleZones: record.compatibleZones as RoomZoneType[],
  defaultScale: record.defaultScale,
  defaultActionType: record.defaultActionType as RoomActionType,
}));

/** Ids of the Interior V1 assets (for the test room + debug surface). */
export const INTERIOR_V1_IDS = interiorV1Assets.map((asset) => asset.id);
