// AUTO-GENERATED by the Nestudio Asset Factory. Do not edit by hand.
// Approved assets, shaped to the Nestudio catalog (CatalogAsset[]).
// Import manually into the main app — see apps/asset-factory/README.md.

export const approvedAssets = [
  {
    "id": "ast-cafe-counter",
    "name": "Cafe Counter",
    "category": "furniture",
    "villageTheme": "any",
    "placement": "floor",
    "ownerType": "system",
    "rarity": "common",
    "tags": ["cafe", "counter", "coffee"],
    "imageUrl": "/samples/cafe-counter.png",
    "status": "published",
    "compatibleZones": ["floor_left", "floor_center", "floor_right"],
    "defaultScale": 1.2,
    "defaultActionType": "product"
  },
  {
    "id": "ast-cozy-reading-chair",
    "name": "Cozy Reading Chair",
    "category": "furniture",
    "villageTheme": "any",
    "placement": "floor",
    "ownerType": "system",
    "rarity": "common",
    "tags": ["chair", "cozy", "reading"],
    "imageUrl": "/samples/cozy-reading-chair.png",
    "status": "published",
    "compatibleZones": ["floor_left", "floor_center", "floor_right"],
    "defaultScale": 1,
    "defaultActionType": "none"
  },
  {
    "id": "ast-leafy-corner-plant",
    "name": "Leafy Corner Plant",
    "category": "plant",
    "villageTheme": "any",
    "placement": "floor",
    "ownerType": "system",
    "rarity": "common",
    "tags": ["plant", "green", "corner"],
    "imageUrl": "/samples/leafy-corner-plant.png",
    "status": "published",
    "compatibleZones": ["floor_left", "floor_right", "shelf"],
    "defaultScale": 0.9,
    "defaultActionType": "none"
  },
  {
    "id": "ast-round-jute-rug",
    "name": "Round Jute Rug",
    "category": "floor",
    "villageTheme": "any",
    "placement": "floor",
    "ownerType": "system",
    "rarity": "common",
    "tags": ["rug", "jute", "round"],
    "imageUrl": "/samples/round-jute-rug.png",
    "status": "published",
    "compatibleZones": ["floor_center"],
    "defaultScale": 1.3,
    "defaultActionType": "none"
  },
  {
    "id": "ast-wooden-market-stall",
    "name": "Wooden Market Stall",
    "category": "structure",
    "villageTheme": "any",
    "placement": "exterior",
    "ownerType": "system",
    "rarity": "common",
    "tags": ["market", "stall", "shop"],
    "imageUrl": "/samples/wooden-market-stall.png",
    "status": "published",
    "compatibleZones": ["floor_left", "floor_center", "floor_right"],
    "defaultScale": 1.2,
    "defaultActionType": "product"
  }
] as const;

export default approvedAssets;
