import {
  CATEGORY_META,
  type AssetCandidate,
  type NestudioCatalogAsset,
} from "@/lib/types";

// Export approved candidates into the Nestudio catalog shape (Task 8). V1 never
// overwrites the main app's lib/assets.ts — it produces JSON + a TS module that a
// human imports manually (see README "Export workflow").

/** Map one candidate to a Nestudio `CatalogAsset`. */
export function toNestudioAsset(candidate: AssetCandidate): NestudioCatalogAsset {
  const meta = CATEGORY_META[candidate.category];
  return {
    id: `ast-${candidate.slug}`,
    name: candidate.name,
    category: meta.nestudioCategory,
    villageTheme: "any",
    placement: candidate.placementType,
    ownerType: "system",
    rarity: "common",
    tags: candidate.tags,
    imageUrl: candidate.imageUrl,
    status: "published",
    compatibleZones: candidate.compatibleZones,
    defaultScale: candidate.defaultScale,
    defaultActionType: candidate.defaultActionType,
  };
}

/** All approved candidates, mapped to catalog assets, sorted by id for stability. */
export function approvedCatalog(candidates: AssetCandidate[]): NestudioCatalogAsset[] {
  return candidates
    .filter((c) => c.status === "approved")
    .map(toNestudioAsset)
    .sort((a, b) => a.id.localeCompare(b.id));
}

/** Pretty JSON export of the approved catalog. */
export function exportJson(candidates: AssetCandidate[]): string {
  return JSON.stringify(approvedCatalog(candidates), null, 2) + "\n";
}

/** A ready-to-import TypeScript module exporting the approved catalog. */
export function exportTs(candidates: AssetCandidate[]): string {
  const assets = approvedCatalog(candidates);
  const body = JSON.stringify(assets, null, 2);
  return (
    "// AUTO-GENERATED by the Nestudio Asset Factory. Do not edit by hand.\n" +
    "// Approved assets, shaped to the Nestudio catalog (CatalogAsset[]).\n" +
    "// Import manually into the main app — see apps/asset-factory/README.md.\n\n" +
    `export const approvedAssets = ${body} as const;\n\n` +
    `export default approvedAssets;\n`
  );
}
