import {
  CATEGORY_META,
  type AssetCandidate,
  type AssetPack,
  type NestudioCatalogAsset,
} from "@/lib/types";

// Export approved candidates into the Nestudio catalog shape (Task 8). V1 never
// overwrites the main app's lib/assets.ts — it produces JSON + a TS module that a
// human imports manually (see README "Export workflow").

/** Map one candidate to a Nestudio `CatalogAsset`. */
export function toNestudioAsset(candidate: AssetCandidate): NestudioCatalogAsset {
  const meta = CATEGORY_META[candidate.category];
  return {
    id: `ast-${candidate.slug}`,
    name: candidate.name,
    category: meta.nestudioCategory,
    villageTheme: "any",
    placement: candidate.placementType,
    ownerType: "system",
    rarity: "common",
    tags: candidate.tags,
    imageUrl: candidate.imageUrl,
    status: "published",
    compatibleZones: candidate.compatibleZones,
    defaultScale: candidate.defaultScale,
    defaultActionType: candidate.defaultActionType,
  };
}

/** All approved candidates, mapped to catalog assets, sorted by id for stability. */
export function approvedCatalog(candidates: AssetCandidate[]): NestudioCatalogAsset[] {
  return candidates
    .filter((c) => c.status === "approved")
    .map(toNestudioAsset)
    .sort((a, b) => a.id.localeCompare(b.id));
}

/** Pretty JSON export of the approved catalog. */
export function exportJson(candidates: AssetCandidate[]): string {
  return JSON.stringify(approvedCatalog(candidates), null, 2) + "\n";
}

/** All saved candidates in raw candidate shape (catalog-candidates.json, V3.7.2). */
export function exportCandidatesJson(candidates: AssetCandidate[]): string {
  const sorted = [...candidates].sort((a, b) => a.id.localeCompare(b.id));
  return JSON.stringify(sorted, null, 2) + "\n";
}

// ── Room-engine catalog (V3.7.3) ─────────────────────────────────────────────
// The room engine receives the approved REAL OpenAI assets — never seed/placeholder
// samples. Extends the Nestudio catalog shape with provenance (personality, source,
// model) so the engine + audits can trace each asset back to its Style Lab origin.

export type RoomEngineAsset = NestudioCatalogAsset & {
  personality?: string;
  source: string;
  modelProvider: string;
  modelName: string;
};

export function toRoomEngineAsset(candidate: AssetCandidate): RoomEngineAsset {
  return {
    ...toNestudioAsset(candidate),
    personality: candidate.personality,
    source: candidate.source ?? "style_lab",
    modelProvider: candidate.modelProvider,
    modelName: candidate.modelName,
  };
}

/** Approved, real OpenAI candidates mapped to the room-engine shape (sorted by id). */
export function roomEngineCatalog(candidates: AssetCandidate[]): RoomEngineAsset[] {
  return candidates
    .filter((c) => c.status === "approved" && c.modelProvider === "openai")
    .map(toRoomEngineAsset)
    .sort((a, b) => a.id.localeCompare(b.id));
}

/** Pretty JSON for nestudio-interior-v1.catalog.json (approved real OpenAI only). */
export function exportRoomEngineCatalog(candidates: AssetCandidate[]): string {
  return JSON.stringify(roomEngineCatalog(candidates), null, 2) + "\n";
}

/** A ready-to-import TypeScript module exporting the approved catalog. */
export function exportTs(candidates: AssetCandidate[]): string {
  const assets = approvedCatalog(candidates);
  const body = JSON.stringify(assets, null, 2);
  return (
    "// AUTO-GENERATED by the Nestudio Asset Factory. Do not edit by hand.\n" +
    "// Approved assets, shaped to the Nestudio catalog (CatalogAsset[]).\n" +
    "// Import manually into the main app — see apps/asset-factory/README.md.\n\n" +
    `export const approvedAssets = ${body} as const;\n\n` +
    `export default approvedAssets;\n`
  );
}

// ── Pack export (V2.5) ───────────────────────────────────────────────────────

/** A pack as exported: its approved members resolved to catalog asset ids. */
export type ExportedPack = {
  id: string;
  slug: string;
  name: string;
  description: string;
  theme: string;
  status: string;
  assetCount: number;
  /** `ast-<slug>` ids of the pack's APPROVED members (so the export is import-ready). */
  assets: string[];
  createdAt: string;
};

/** Resolve packs to their approved members in Nestudio id form. */
export function packsForExport(packs: AssetPack[], candidates: AssetCandidate[]): ExportedPack[] {
  const approvedById = new Map(candidates.filter((c) => c.status === "approved").map((c) => [c.id, c]));
  return packs.map((pack) => {
    const assets = pack.assetIds
      .map((id) => approvedById.get(id))
      .filter((c): c is AssetCandidate => !!c)
      .map((c) => `ast-${c.slug}`)
      .sort((a, b) => a.localeCompare(b));
    return {
      id: pack.id,
      slug: pack.slug,
      name: pack.name,
      description: pack.description,
      theme: pack.theme,
      status: pack.status,
      assetCount: assets.length,
      assets,
      createdAt: pack.createdAt,
    };
  });
}

/** Pretty JSON export of the packs (with resolved approved members). */
export function exportPacksJson(packs: AssetPack[], candidates: AssetCandidate[]): string {
  return JSON.stringify(packsForExport(packs, candidates), null, 2) + "\n";
}
